### ISSUE TITLE
Support for dynamic height

### ISSUE THREAD

**Issue by iRILLLL** [super-ultra/UltraDrawerView#11]
is it possible to add support dynamic height for the sheet?

**Comment by super-ultra** [comment]
What do you mean? You mean dynamic top anchor?

**Comment by iRILLLL** [comment]
yes, 
I want to middle position based on scroll view's intrinsic content size

currently I'm doing 
```
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        let contentHeight = tableView.contentSize.height + Layout.headerHeight 
        let viewHeight = view.frame.size.height
        if contentHeight < viewHeight {
            drawerView.middlePosition = .fromBottom(contentHeight)
        }
    }
```

are there other recommended ways? Thanks

![Simulator Screen Shot - iPod touch (7th generation) - 2021-04-02 at 07 30 55](https://user-images.githubusercontent.com/6050254/113367420-288a8700-9386-11eb-9edf-41ba7da896f1.png) ![Simulator Screen Shot - iPod touch (7th generation) - 2021-04-02 at 07 31 14](https://user-images.githubusercontent.com/6050254/113367423-29bbb400-9386-11eb-84fe-5b39b61e913a.png)

**Comment by super-ultra** [comment]
Take a look at `DrawerView.RelativePosition`. It has `ignoresContentSize` property. If you pass `false`, the `contentSize` will be used to calculate the position.

For example: 
```swift
drawerView.topPosition = .fromTop(Layout.topInsetLandscape, ignoresContentSize: false)
```
Maybe this is what you need?

**Comment by iRILLLL** [comment]
that's it.
Thank you very much for your time to help!
