### ISSUE TITLE
Swift Package Manager?

### ISSUE THREAD

**Issue by pierre-wehbe** [super-ultra/UltraDrawerView#2]

**Comment by super-ultra** [comment]
Good idea. I will add Package Manager support soon.

**Comment by super-ultra** [comment]
UltraDrawerView supports Swift Package Manager now. 
Sorry for the delay.

**Comment by cyberpoussin** [comment]
UltraDrawerView works fine with CocoaPods but when I try to add it with SPM (Xcode 12.4) I obtain the following Swift Compiler error : 
"Cannot find type 'CGFloat' in scope; did you mean to use 'CGFloat'?"
in `public extension AnimationParameters `
in `static func spring`

**Comment by super-ultra** [comment]
My fault.
This file should contain `import CoreGraphics`.
I will fix it.
Thanks
