### ISSUE TITLE
После удаления библиотеки pop начались проблемы с DrawerViewListener

### ISSUE THREAD

**Issue by subdan** [super-ultra/UltraDrawerView#6]
После удаления библиотеки **pop** начались следующие проблемы:

1. Если свайпнуть `DrawerView` вверх из положения `.middle` в `.top`, то значение `origin` переданное в метод `didUpdateOrigin` не будет равно конечному значению. 

https://user-images.githubusercontent.com/410293/104882168-a1776680-5973-11eb-9e22-1101bf06cfb4.mov

На видео видно что origin равен `84.00379903889234`, а должен быть равен `84.0`.

2. Метод `didUpdateOrigin` стал вызываться после того как анимация завершилась. На видео выше видно что этот метод продолжает вызывается после завершения анимации. Если откатить на версию с библиотекой pop то такой проблемы нет.

3. Метод `didUpdateOrigin` стал вызываться сильно чаще чем было до этого.

Сейчас если свайпнуть `DrawerView` вверх из положения `.middle` в `.top`, то метод `didUpdateOrigin` вызовется 67 раз, а до удаления библиотеки pop этот метод вызывался 33 раза.

**Обсудить:**
 
Можно ли сделать так чтобы он вызывался только при изменении целой части значения `origin`? То есть вместо такого:

```
86.85568667733486
86.30025473571135
85.5273588069822
85.23997177933157
84.99605378858263
84.80715678836103
84.6612911479868
84.52847303222093
84.43310181664573
84.34548088841095
84.28263115720186
84.22836565102469
84.18343991245922
84.14671614414095
84.11868051209942
84.09659951398588
84.07680739856822
84.06187182913489
84.04981766151992
84.04036396309593
84.03225499286657
84.02619147637247
84.02112442808475
84.01677026171919
84.01347722976746
84.01082530400531
84.00869548762955
84.00698126842899
84.00566759573098
84.0044962094914
84.00420290465807
```
получить такое:
```
86
85
84
```

**Comment by super-ultra** [comment]
Спасибо за такое подробное описание.
1. Починил.
2. `didUpdateOrigin` вызывался из-за того, что анимация очень плавно приближалась к конечной точке. Настолько плавно, что это движение было незаметным. Я увеличил порог, и теперь `didUpdateOrigin` заканчивает вызываться быстрее.
3. Я использую `CADisplayLink`, и он синхронизирован с частотой обновления дисплея. Я добавил опцию `preferredAnimationFramesPerSecond`, может это будет полезным для оптимизации, но я бы рекомендовал оставить значение по умолчанию.

> Можно ли сделать так чтобы он вызывался только при изменении целой части значения origin? 
Это, вообще говоря, может быть недостаточным для клиентов. Особенно если они привязали к `origin` какие-нибудь свои вью. Целые значения будут приводить к ступенчатой анимации. 
Думаю, что если клиент хочет выполнять действия реже, то он может на своей стороне пропускать часть событий `didUpdateOrigin` и обрабатывать только целочисленные изменения.

**Comment by subdan** [comment]
Спасибо!

Если честно, меня не устраивает новая анимация движения карточки. Она стала длиннее и очень долго завершается. Можно ли как-то настроить её параметры?

Можно ли заменить анимацию не редактируя исходники? Я например хочу использовать easeOut анимацию т.к. spring-анимация мне не нужна (я отключил bounce).

Я построил график анимации UltraDrawerView 5.0.0:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/410293/104997699-15307680-5a3b-11eb-8001-10c67164c669.png">
Видно что вторую половину продолжительности анимации карточка почти не движется.
didUpdateOrigin вызвался 57 раз.

Так же построил график анимации UltraDrawerView 3.0.0:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/410293/104998180-d3ec9680-5a3b-11eb-9c96-d1cfa3b72fff.png">
Здесь последнюю треть продолжительности анимации карточка почти не движется. Это нормально с учетом того что didUpdateOrigin вызвался всего 31 раз.

Если наложить обе анимации видна разница.
<img width="536" alt="image" src="https://user-images.githubusercontent.com/410293/104998319-0eeeca00-5a3c-11eb-97a5-541aa66b1d16.png">

**Comment by super-ultra** [comment]
Добрый вечер. 
Прошу прощения за такую задержку. 
Текущие настройки анимации отличаются от предыдущих, но они ближе к стандартному поведению UIScrollView, поэтому я оставил их по умолчанию.

Но сейчас в версии 0.6.1 я добавил возможность контролировать параметры анимации:
drawerView.animationParameters = .spring(mass: 1, stiffness: 200, dampingRatio: 1)

Если вы хотите сделать поведение более резким, то увеличьте параметр stiffness, если хотите добавить колебаний, то уменьшите параметр dampingRatio (например, до 0.8).

Кроме этого, я поправил проблему того, что ближе к концу анимации, когда движения почти не было, анимация все равно продолжалась. 
Так было из-за того, что время анимации высчитывалось заранее, и это было не совсем точно. Теперь время не используется совсем — анимация завершается, когда амплитуда приближается к нулю.
Это помогло уменьшить количество вызовов. 

Если будут вопросы, пишите.

Спасибо

**Comment by subdan** [comment]
Спасибо, Илья.
